### ISSUE TITLE
Fix broken CI build

### ISSUE THREAD

**Issue by Roshanjossey** [funretro/distributed#137]
Here's the error I got from CI
```
/var/snap-ci/repo/node_modules/gulp-sourcemaps/node_modules/strip-bom/index.js:2
module.exports = x => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/snap-ci/repo/node_modules/gulp-sourcemaps/src/init/index.internals.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/snap-ci/repo/node_modules/gulp-sourcemaps/src/init/index.js:10:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Command gulp testci failed with status 8.
Execution took 0m1.2s.
Saving console log for later
```
I googled around a bit about this and this is what I got

http://stackoverflow.com/questions/40220506/gulp-sourcemaps-syntaxerror-unexpected-token

When I try gulp testci from my local, it does pass. I'm using node version 5.5.0
When I looked through CI trace, I learned that were using node v0.10.37 (npm v1.4.28)

As discussed in #128, we should update node and gulp-sass

@glauberramos, I'm adding this as another issue so it'd be easy to track

**Comment by glauberramos** [comment]
I was thinking more about this, and I think we should change to Travis CI. Since Snap ci is going away. https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/

**Comment by Roshanjossey** [comment]
Travis is common for most open source projects. Do you wanna spend some time to look in to other tools as well? Like werker , circleci, bamboo or go cd ?

**Comment by glauberramos** [comment]
Hummm, our build process is very simple, only run unit tests and then run deploy script. So I think Travis CI should be enough for us.

**Comment by glauberramos** [comment]
I just added travis CI and the build is working.
