### ISSUE TITLE
Can't create board with IE11

### ISSUE THREAD

**Issue by skenefick** [funretro/distributed#190]
Create button is permanently disabled in Internet Explorer 11.

![image](https://user-images.githubusercontent.com/4314681/27654751-9c3cd09a-5c08-11e7-974b-d2558a244372.png)

Here is the console error:
`TypeError: Object doesn't support property or method 'isInteger'
   at $scope.isMaxVotesValid (http://funretro.github.io/distributed/main.js:226:9)
   at fn (Function code:2:354)
   at h.prototype.$digest (http://funretro.github.io/distributed/vendor.js:3:4862)
   at h.prototype.$apply (http://funretro.github.io/distributed/vendor.js:3:6455)
   at Anonymous function (http://funretro.github.io/distributed/vendor.js:5:11554)
   at jt (http://funretro.github.io/distributed/vendor.js:1:14803)
   at n (http://funretro.github.io/distributed/vendor.js:1:14752)`

It looks like the vote validation is using an ES6 method that is not supported by older browsers. Unfortunately, some companies don't have modern browsers available on all machines. 

Number.isInteger documentation with polyfill for old browsers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by glauberramos** [comment]
That's a good point, thanks for finding it. Are you keen to open a PR for that? It should be simple to fix.
